### PR TITLE
Add initial support to multiple events

### PR DESCRIPTION
**Pull request by Williangalvani**
We need to think of the UI,
it currently looks like this:
Screenshot from 2020-03-29 13-55-20

### CODE REVIEW

**Comment by Williangalvani** [comment]
we could do it like this:
image
but I think pollutes too much

**Comment by Williangalvani** [comment]
maybe this?
image

**Comment by patrickelectric** [comment]
Maybe you could create a toggle ? Is it useful to have all this information at once ?
I believe that it's necessary to understand what is the objective and what the user would like to do with this information and what information the user will want to look at.

**Comment by kd0aij** [comment]
I think the way APMplanner2 does it is OK with the toggle to turn message display on and off.

**Comment by Williangalvani** [comment]
This is already on master

**Pull request closed without merging**
