### PR TITLE
Resolves #267, #268

### LINKED ISSUE #267: TAKEOFF Flight Mode, not properly shown in the list of modes
image

The brown/orange secion on the timeline is takeoff mode and this is not correctly shown in the list of modes.

### PR DESCRIPTION
**Pull request by teodoryantcheff**
Resolves #267, #268

### CODE REVIEW

**Comment by teodoryantcheff** [comment]
Not sure why the tests are failing. Some help would be appreciated.

**Comment by Williangalvani** [comment]
thanks for the pr @teodoryantcheff !

The tests are fetching logs from ardupilot autotest, and sometimes thinks break over there and the tests fail here...
So, don't worry about it.

**Comment by teodoryantcheff** [comment]
I did run `test/testlogfiles/logdownloader.sh` locally and it successfully got me the files, tests still fail with the same errors, though :
```parse tlogs › parse /tmp/testlogs/ArduPlane-test.tlog

    expect(received).toBeGreaterThan(expected)

    Expected: > 100
    Received:   1

      24 |         expect(Object.keys(messageTypes)).toContain('HEARTBEAT')
      25 |         expect(MavlinkDataExtractor.extractEvents(messages).length).toBeGreaterThan(0)
    > 26 |         expect(Object.keys(MavlinkDataExtractor.extractAttitudes(messages)).length).toBeGreaterThan(100)
         |                                                                                     ^
      27 |         expect(MavlinkDataExtractor.extractFlightModes(messages).length).toBeGreaterThan(0)
      28 | 
      29 |         expect(MavlinkDataExtractor.extractParams(messages)).toBeDefined()

      at test/unit/specs/mavlinklogs.spec.js:26:85

  ● parse tlogs › parse /tmp/testlogs/HeliCopter-test.tlog

    TypeError: Cannot read property 'time_boot_ms' of undefined

      184 |             return new Date(lastmsg[0] / 1e3 + lastmsg[1] * ((2 ** 32) / 1e3))
      185 |         } catch {
    > 186 |             let timeUsec = instance.messages['GPS_RAW_INT'].time_boot_ms[0]
          |                                                             ^
      187 |             return new Date(timeUsec * ((2 ** 32) / 1e3))
      188 |         }
      189 |     }

      at MavlinkParser.extractStartTime (src/tools/parsers/mavlinkParser.js:186:61)
      at MavlinkParser.processData (src/tools/parsers/mavlinkParser.js:230:29)
      at test/unit/specs/mavlinklogs.spec.js:21:31```

Both of which, to me at least, tells me that the test files are "broken" from the perspective of what the test suite expects them to contain.

**Review by Williangalvani — APPROVED** [review]

**Comment by teodoryantcheff** [comment]
Done.

**Pull request merged**
